### ISSUE TITLE
Wrong automatic fix for "!= None" vs "is not None"

### ISSUE THREAD

**Issue by Unode** [quantifiedcode/issues#51]
On the same code there were occurrences of:
    if x != None:

as well as:
    if x!=None:

The first were automatically corrected to:
    if x is not None:

but the second was corrected to:
    if xis notNone:

Which is obviously wrong.

**Comment by adewes** [comment]
Thanks for reporting this @Unode , this is of course an error! We'll fix it immediately and should have it deployed by tomorrow. I'll get back to you as soon as it's done.

**Comment by adewes** [comment]
We deployed a new version, please let us know if it fixes your problem!

**Comment by Unode** [comment]
Tested just now. The patch received is still incorrect:

    -        if fcn1!=None:
    +        if fcn1is notNone:

**Comment by Unode** [comment]
And a more complex case:

    -     elif limits[0]==None and limits[1]!=None:
    +     elif limits[0]isNone and limits[1]is notNone:

**Comment by adewes** [comment]
Just a minute, I'll have a look at it.

**Comment by adewes** [comment]
hm okay, I can reproduce the problem, will fix this asap.

**Comment by benroeder** [comment]
any news on the fix ?

**Comment by adewes** [comment]
Hey @benroeder , sorry for the delay, I'll have a look at this in the coming days and get back to you!

Best
Andreas

**Comment by adewes** [comment]
Dear @benroeder , I just deployed a fix for this issue, please let me know if this fixes your problems! Sorry again for the delay, if you have any other problems please don't hesitate to contact me directly via e-mail at andreas@quantifiedcode.com

Best
Andreas
